grpcサーバーの集約
ca-risken/core pull request #258
Opened 2022-04-27 04:44 UTC by hnts

2022-05-08 23:42 UTC, mmmknt requested changes
CIを通すか、通らないなら問題ないことを確認したかを教えてください 🙏

2022-05-09 01:28 UTC, hnts commented
@mmmknt 

codebuildの対応は後ほどさせていただきます。
動作確認については今のところ問題ないです。

2022-05-09 01:47 UTC, mmmknt requested changes
linterかけたら検知されたので対応お願いします
```
$ golangci-lint run
pkg/db/mocks/project.go:54:29: func `(*mockProjectClient).DeleteAllProjectRole` is unused (unused)
func (m *mockProjectClient) DeleteAllProjectRole(context.Context, uint32) error {
                            ^
pkg/db/mocks/project.go:46:6: type `mockProjectClient` is unused (unused)
type mockProjectClient struct {
     ^
pkg/db/mocks/project.go:50:29: func `(*mockProjectClient).CreateDefaultRole` is unused (unused)
func (m *mockProjectClient) CreateDefaultRole(context.Context, uint32, uint32) error {
                            ^
pkg/db/mocks/project.go:58:29: func `(*mockProjectClient).IsActiveProject` is unused (unused)
func (m *mockProjectClient) IsActiveProject(ctx context.Context, projectID uint32) (bool, error) {
                            ^
```

2022-05-09 09:25 UTC, mmmknt commented on pkg/server/server.go
> +		s.logger.Fatalf("faild to get grpc connection: err=%+v", err)
typo: faild -> failed

2022-05-09 09:25 UTC, mmmknt commented on pkg/server/server.go
> +		s.logger.Fatalf("faild to get grpc connection: err=%+v", err)
typo: faild -> failed

2022-05-09 10:57 UTC, gassara-kys commented on Makefile
> +			-I $(GOPATH)/pkg/mod/github.com/envoyproxy/protoc-gen-validate@v0.6.7 \
moduleのversion指定があるのでmake installの箇所もあわせてversion指定してインストールするほうが良さそうです。

```
go get github.com/envoyproxy/protoc-gen-validate@v0.6.7
```

2022-05-09 10:57 UTC, gassara-kys commented on pkg/server/server.go
> +		grpc.WithUnaryInterceptor(xray.UnaryClientInterceptor()),
xray削除のタイミングでxray.UnaryClientInterceptor()が不要かと思います。

2022-05-09 10:57 UTC, gassara-kys commented on Dockerfile
>  RUN echo "password $GITHUB_TOKEN" >> ~/.netrc
既存実装の消し忘れですが、GitHubのクレデンシャルを~/.netrcに書き込む処理不要でした。こちら削除お願いできますか？

2022-05-10 01:14 UTC, hnts commented on pkg/db/alert.go
> +var _ AlertRepository = (*Client)(nil)
interfaceがきちんと実装されているかを確認するときのテクニックですね
https://github.com/uber-go/guide/blob/master/style.md#verify-interface-compliance

手癖みたいなもので、僕はいつも書いています

2022-05-10 02:19 UTC, gassara-kys approved these changes
LGTM

2022-05-10 03:11 UTC, iiiidaaa commented on pkg/db/iam.go
> +		return fmt.Errorf("Not found user: user_id=%d", userID)
errorメッセージが大文字スタートになっているので小文字に直していくのが良さそうです。
とはいえ、ここ含めて既存の実装の問題だと思うので備忘録として残しておきます。(他の箇所もあった)

2022-05-10 03:16 UTC, iiiidaaa commented on pkg/server/alert/alert_analyze.go
>  	projectproto "github.com/ca-risken/core/proto/project"
github.com/ca-risken/core/proto/project を2回インポートしてそうです。
既存の部分が projectproto.Hogehogeで呼ばれていたのに対して、(おそらく)移動されたGetPayloadがproject.Projectで呼ばれてるせいですかね？

2022-05-10 03:24 UTC, iiiidaaa commented on Makefile
> +.PHONY: list-report-service
reportサービス向けのgrpcurlがlocalhostを向いているので、他と合わせてcore.core.svc.cluster.local:8080に向けるのが良いかと思います。
(既存の問題のはず、ごめんなさい)

2022-05-10 03:49 UTC, mmmknt commented on pkg/db/alert.go
> +var _ AlertRepository = (*Client)(nil)
確かにinterfaceのチェックができますね。教えてくれてありがとうございます！

2022-05-10 03:54 UTC, mmmknt approved these changes
LGTM!

2022-05-10 03:55 UTC, iiiidaaa approved these changes
LGTM

2022-05-10 04:05 UTC, merged