Upgrade go version
ca-risken/core pull request #265
Opened 2022-05-18 02:14 UTC by hnts

Goのバージョンを1.18に上げます。

2022-05-18 03:15 UTC, mmmknt requested changes
ここと
https://github.com/ca-risken/core/blob/master/codebuild/multi-arch/install-go.sh#L2
CI用のジョブ定義の中で設定しているGoのバージョンも変更する必要があるので対応お願いします:pray:
```
version: 0.2

env:
  variables:
    IMAGE_PREFIX: "risken-core"
    INSTALL_GO_VERSION: "1.17.1"
```

2022-10-24 07:41 UTC, gassara-kys reviewed
現状、 codebuild側で1.18がサポートされていますが、今後を考えるとCodebuildのサポートが遅れることが多いのでinstall-go.shで自分たちでバージョン管理することのほうが利点が多いと考えます
https://docs.aws.amazon.com/ja_jp/codebuild/latest/userguide/runtime-versions.html

2022-10-24 07:42 UTC, gassara-kys approved these changes
LGTM 
conflictの解消お願いします :pray:

2022-10-25 03:01 UTC, gassara-kys approved these changes

2022-10-25 03:04 UTC, merged