Implement healthz endpoint
ca-risken/core pull request #266
Opened 2022-05-18 08:15 UTC by hnts

healthzのエンドポイントを用意しました。

2022-05-18 09:11 UTC, mmmknt requested changes
以下のPRがマージされてloggerのIFが変わっているのでコンパイルが失敗するようになってると思います。
ログ出力用の関数の最初の引数にcontext.Contextを渡すようにしてください。
https://github.com/ca-risken/core/pull/264/files

2022-05-18 10:13 UTC, mmmknt reviewed
HTTPとgRPCのエンドポイントがそれぞれあるみたいですが、なんででしたっけ？

2022-05-18 13:01 UTC, gassara-kys commented
Liveness Probe、Readiness Probe、 Startup ProbeのためのヘルスチェックをKubernetesがネイティブサポートしているhttp経由でやりたいという意図があるのかなという理解でした。

別の方法としてgRPCサーバのコンテナにgrpc_health_probeをインストールしてヘルスチェック実現するやりかたもあるみたいですが（これだとhttpサーバーのエンドポイント作る必要はなさそう）、どちらが良いのかはやったことないのでよくわかってないです。
https://cloud.google.com/blog/topics/developers-practitioners/health-checking-your-grpc-servers-gke

2022-05-19 03:54 UTC, mmmknt approved these changes
👍

2022-05-19 05:15 UTC, hnts commented
@mmmknt @gassara-kys 

コメントありがとうございます！
httpのエンドポイントを用意しているのは、小笠原さんがおっしゃっている通り、kubernetesがネイティブでサポートしているからですね(まだRISKENのeksはgrpcのprobeに対応していない)
https://github.com/ca-risken/core/pull/266#issuecomment-1129988268
一方grpc_health_probeをインストールする方法もあります！
しかし「コンテナに余計なバイナリを含めたくない && argo-cdも同じような構成をとっていて事例がある」ということでhttpエンドポイントを使うように今回はしました
RISKENのeksでgrpcのprobeをサポートしたらhttpエンドポイントは消そうかなと思っています！

2022-05-19 05:16 UTC, merged