rm: regexp SQL
ca-risken/core pull request #276
Opened 2022-07-20 07:31 UTC by gassara-kys

パフォーマンスの問題でSQLで `regexp` 条件を使用している箇所をLIKEに変更します。
また、DBのindexが利用されるよう前方一致検索に変更します
（これまで、部分一致検索を許容していたので機能劣化になります。RISKEN内のシステムで部分一致を利用しているユースケースがないのと、システムパフォーマンスを優先する判断です）

2022-07-20 08:12 UTC, mmmknt requested changes

2022-07-20 08:12 UTC, mmmknt commented on pkg/db/finding.go
> +		if p == "" {
pが空文字になる場合ってあるんでしょうか？
もしあるなら、paramsが`{""}`の場合に呼び出し元の以下のコードでsqlが空文字になり、クエリを実行した際にinvalidな条件としてエラーになりそうです。
クエリを実行する前にエラーで弾くか、問題ないクエリを発行するようにできないでしょうか？
`query += fmt.Sprintf(" and (%s)", sql)`

2022-07-20 09:34 UTC, gassara-kys commented on pkg/db/finding.go
> +		if p == "" {
実際にAPIを実行し空文字のパラメータが通るか確認したところ、エラーになりました。
ご指摘ありがとうございます。

問題のないクエリを発行するよう修正します

2022-07-20 09:34 UTC, gassara-kys commented on pkg/db/finding.go
> +		if p == "" {
呼び出し元の方で判定する処理を入れ、SQL構文エラーになってしまうケースを回避しました:pray:

2022-07-21 04:23 UTC, mmmknt approved these changes
LGTM

2022-07-21 06:03 UTC, merged